// <auto-generated />
using System;
using FantasyBookShop.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FantasyBookShop.Server.Migrations
{
    [DbContext(typeof(FantasyBookShopContext))]
    [Migration("20230324100732_featuredFlagAdded")]
    partial class featuredFlagAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("FantasyBookShop.Shared.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "J.R.R. Tolkien"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Charles Soule"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Andrzej Sapkowski"
                        },
                        new
                        {
                            Id = 4,
                            Name = "John Flanagan"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mike Chen"
                        });
                });

            modelBuilder.Entity("FantasyBookShop.Shared.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Featured")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The Lord of the Rings is an epic[1] high-fantasy novel[a] by English author and scholar J. R. R. Tolkien. Set in Middle-earth, the story began as a sequel to Tolkien's 1937 children's book The Hobbit, but eventually developed into a much larger work. Written in stages between 1937 and 1949, The Lord of the Rings is one of the best-selling books ever written, with over 150 million copies sold.",
                            Featured = true,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/e/e9/First_Single_Volume_Edition_of_The_Lord_of_the_Rings.gif",
                            PublishDate = new DateTime(1954, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Lord of the rings"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Star Wars: The High Republic: Light of the Jedi is the first novel of the Star Wars: The High Republic multi-media project launched in 2021. The novel was written by Charles Soule, and is set approximately 200 years before the events of Star Wars: The Phantom Menace. It was followed by a sequel, The Rising Storm.",
                            Featured = true,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/2/21/LOTJ_cover.jpg",
                            PublishDate = new DateTime(2021, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "High Republic: Light of the Jedi"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The Witcher (Polish: Wiedźmin) is a series of six fantasy novels and 15 short stories written by Polish author Andrzej Sapkowski. The series revolves around the eponymous \"witcher\", Geralt of Rivia. In Sapkowski's works, \"witchers\" are beast hunters who develop supernatural abilities at a young age to battle wild beasts and monsters. The Witcher began with a titular 1986 short story that Sapkowski entered into a competition held by Fantastyka magazine, marking his debut as an author. Due to reader demand, Sapkowski wrote 14 more stories before starting a series of novels in 1994. Known as The Witcher Saga, he wrote one book a year until the fifth and final installment in 1999. A standalone prequel novel, Season of Storms, was published in 2013.",
                            Featured = true,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/1/14/Andrzej_Sapkowski_-_The_Last_Wish.jpg",
                            PublishDate = new DateTime(1993, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Witcher"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Ranger's Apprentice is a series written by Australian author John Flanagan. It began as twenty short stories Flanagan wrote for his son to get him interested in reading. Ten years later, Flanagan found the stories again and decided to turn them into a book, which became the first novel in the series, The Ruins of Gorlan. It was originally released in Australia on 1 November 2004. Though the books were initially published only in Australia and New Zealand, they have since been released in 14 other countries.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/d/d8/The_Ruins_of_Gorlan.jpg",
                            PublishDate = new DateTime(2004, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ranger's Apprentice"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Obi-Wan Kenobi and Anakin Skywalker must stem the tide of the raging Clone Wars and forge a new bond as Jedi Knights.\r\nThe Clone Wars have begun. Battle lines are being drawn throughout the galaxy. With every world that joins the Separatists, the peace guarded by the Jedi Order is slipping through their fingers.",
                            Featured = false,
                            ImageUrl = "https://static.wikia.nocookie.net/starwars/images/3/3d/Brotherhood_Final_Cover.png/revision/latest/scale-to-width-down/1000?cb=20220510224638",
                            PublishDate = new DateTime(2022, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars: Brotherhood"
                        });
                });

            modelBuilder.Entity("FantasyBookShop.Shared.BookAuthor", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookAuthor");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 2
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 3
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 4
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 5
                        });
                });

            modelBuilder.Entity("FantasyBookShop.Shared.BookCategory", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BookCategory");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 1,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 2,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 3,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 5,
                            CategoryId = 3
                        });
                });

            modelBuilder.Entity("FantasyBookShop.Shared.BookType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BookTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hard Cover Book"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Paperback Book"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Audio Book"
                        },
                        new
                        {
                            Id = 4,
                            Name = "E-Book"
                        });
                });

            modelBuilder.Entity("FantasyBookShop.Shared.BookVariant", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BookId", "BookTypeId");

                    b.HasIndex("BookTypeId");

                    b.ToTable("BookVariants");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            BookTypeId = 1,
                            OriginalPrice = 40m,
                            Price = 20m
                        },
                        new
                        {
                            BookId = 1,
                            BookTypeId = 2,
                            OriginalPrice = 20m,
                            Price = 10m
                        },
                        new
                        {
                            BookId = 1,
                            BookTypeId = 4,
                            OriginalPrice = 10m,
                            Price = 5m
                        },
                        new
                        {
                            BookId = 2,
                            BookTypeId = 2,
                            OriginalPrice = 30m,
                            Price = 15m
                        },
                        new
                        {
                            BookId = 2,
                            BookTypeId = 4,
                            OriginalPrice = 10m,
                            Price = 5m
                        },
                        new
                        {
                            BookId = 3,
                            BookTypeId = 2,
                            OriginalPrice = 25m,
                            Price = 15m
                        },
                        new
                        {
                            BookId = 3,
                            BookTypeId = 3,
                            OriginalPrice = 25m,
                            Price = 15m
                        },
                        new
                        {
                            BookId = 4,
                            BookTypeId = 1,
                            OriginalPrice = 40m,
                            Price = 20m
                        },
                        new
                        {
                            BookId = 4,
                            BookTypeId = 2,
                            OriginalPrice = 30m,
                            Price = 15m
                        },
                        new
                        {
                            BookId = 5,
                            BookTypeId = 2,
                            OriginalPrice = 40m,
                            Price = 20m
                        });
                });

            modelBuilder.Entity("FantasyBookShop.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fantasy",
                            Url = "Fantasy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dark Fantasy",
                            Url = "DarkFantasy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sci-Fi",
                            Url = "SciFi"
                        });
                });

            modelBuilder.Entity("FantasyBookShop.Shared.BookAuthor", b =>
                {
                    b.HasOne("FantasyBookShop.Shared.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyBookShop.Shared.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("FantasyBookShop.Shared.BookCategory", b =>
                {
                    b.HasOne("FantasyBookShop.Shared.Book", "Book")
                        .WithMany("BookCategories")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyBookShop.Shared.Category", "Category")
                        .WithMany("BookCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FantasyBookShop.Shared.BookVariant", b =>
                {
                    b.HasOne("FantasyBookShop.Shared.Book", "Book")
                        .WithMany("Variants")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyBookShop.Shared.BookType", "BookType")
                        .WithMany()
                        .HasForeignKey("BookTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("BookType");
                });

            modelBuilder.Entity("FantasyBookShop.Shared.Author", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("FantasyBookShop.Shared.Book", b =>
                {
                    b.Navigation("BookAuthors");

                    b.Navigation("BookCategories");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("FantasyBookShop.Shared.Category", b =>
                {
                    b.Navigation("BookCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
